name: Test

on:
  push:
  pull_request:


jobs:
  firefox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: [ '80.0', 'latest' ]
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: |
          echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: "lts"
           cache: "npm"
      - run: npm ci
      - run: npm run test --browser=firefox
  chrome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chrome: [ '80.0', 'latest' ]
    name: Chrome ${{ matrix.chrome }} sample
    steps:
      - name: Setup chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ matrix.chrome }}
      - run: |
          echo Installed chrome versions: ${{ steps.setup-chrome.outputs.chrome-version }}
          ${{ steps.setup-chrome.outputs.chrome-path }} --version
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: "lts"
           cache: "npm"
      - run: npm ci
      - run: npm run test --browser=chrome
  node:
    runs-on: ubuntu-latest
    name: Node
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
           node-version: "lts"
           cache: "npm"
      - run: npm ci
      - run: npm run test
  bun:
    runs-on: ubuntu-latest
    name: Bun
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run test
